### ISSUE TITLE
tensorflow报错

### ISSUE THREAD

**Issue by chaohuang** [ACL2020SpellGCN/SpellGCN#10]
我现在用原始的数据测试SpellGCN，但遇到以下错误：

![image](https://user-images.githubusercontent.com/1179764/88863673-39ac4400-d1b8-11ea-91a6-613bfd98b463.png)

请问怎么解决呢？谢谢！

**Comment by V-Enzo** [comment]
![image](https://user-images.githubusercontent.com/18146606/89098436-387a5180-d41a-11ea-8286-d32e8ffbad9b.png)
我也碰到了这个问题，是因为tf的版本问题造成的 你可以升级到1.14或者像图里那样改一下 @chaohuang

**Comment by chaohuang** [comment]
@V-Enzo 嗯，升级到1.14就可以了，谢谢回复。

**Comment by li-aolong** [comment]
readme里写的1.13.1竟然还报错。。
