### ISSUE TITLE
为什么relation_vocab.txt中的关系只有三种？

### ISSUE THREAD

**Issue by li-aolong** [ACL2020SpellGCN/SpellGCN#11]
`data/gcn_graph.ty_xj/relation_vocab.txt`中只有如下三种关系：
```
同音同调 0
同音异调 0
形近 1
```
但是`data/gcn_graph.ty_xj/spellGraphs.txt`中除了以上三种还有`近音同调`，`近音异调`和`同部首同笔画`，为什么这三种被忽略了呢？

**Comment by wead-hsu** [comment]
因为别的后来经过测试没有正向作用

**Comment by li-aolong** [comment]
@wead-hsu 哦哦感谢回复。还想问下，为什么文中说是3层gcn效果最好，但是代码中默认是2层。文中说epoch为6次，代码中默认是10，是按哪个参数效果最好呢？
我只修改源代码的batch size从32改为16，其它参数不变，最终结果，在2013和2014上还比较接近，在sighan2015的指标上平均低5个点左右，这正常么？

**Comment by wead-hsu** [comment]
按照代码来；结果会有一定波动，但是不会差那么多

**Comment by li-aolong** [comment]
@wead-hsu 好的，感谢回复
