### ISSUE TITLE
训练数据集

### ISSUE THREAD

**Issue by Baililily** [ACL2020SpellGCN/SpellGCN#14]
论文中训练数据集是281379条数据，项目中只有10052条数据，请问在哪里可以获取论文中的训练数据呢

**Comment by Sarah-Callies** [comment]
同求啊

**Comment by Aloha0424** [comment]
https://github.com/wdimmy/Automatic-Corpus-Generation/tree/master/corpus 这里面的train.sgml 就是论文中额外的训练集
