### ISSUE TITLE
论文中LMC baseline模型的Character-level指标，在SIGHAN15 上的结果可能写成了在SIGHAN14上的结果

### ISSUE THREAD

**Issue by aloha12345x** [ACL2020SpellGCN/SpellGCN#19]
论文中展示main results的Table 3，LMC baseline模型，Character-level指标，在SIGHAN15 上的结果可能写成了在SIGHAN14上的结果。

![image](https://user-images.githubusercontent.com/76142801/103253616-dae43400-49bc-11eb-9f35-f9225a8114f4.png)

这是Wang et al., 2019中作者重新实现LMC模型后测的结果

![image](https://user-images.githubusercontent.com/76142801/103253653-ff401080-49bc-11eb-9100-a7c04763b23c.png)

另外还有一个问题，Wang et al., 2019中并没有说他报的结果是sentence leve还是character level，我自己的理解，以及调研的相关工作，我感觉应该是sentence level的指标吧

**Comment by rarae** [comment]
Wang et al., 2019的是character level，详见源码https://github.com/sunnyqiny/Confusionset-guided-Pointer-Networks-for-Chinese-Spelling-Check/blob/master/utils/evaluation_metrics.py

**Comment by wead-hsu** [comment]
感谢指正，我们会修正论文中的错误。
