### ISSUE TITLE
ValueError: Couldn't find 'checkpoint' file or checkpoints in given directory log/spellgcn_rep0_sighan13_CSC_0

### ISSUE THREAD

**Issue by rejae** [ACL2020SpellGCN/SpellGCN#5]
Thanks for your opening this repository, I just follow the README instruction and got this error.
It seems like missing finetuned model files.
when will you release the finetuned model file? Thanks for your reply.

**Comment by w5688414** [comment]
I got the same error
```
  File "/home/wugaosheng/SpellGCN/modeling.py", line 329, in get_assignment_map_from_checkpoint
    init_vars = tf.train.list_variables(init_checkpoint)
  File "/home/wugaosheng/.local/lib/python3.6/site-packages/tensorflow/python/training/checkpoint_utils.py", line 97, in list_variables
    reader = load_checkpoint(ckpt_dir_or_file)
  File "/home/wugaosheng/.local/lib/python3.6/site-packages/tensorflow/python/training/checkpoint_utils.py", line 65, in load_checkpoint
    "given directory %s" % ckpt_dir_or_file)
ValueError: Couldn't find 'checkpoint' file or checkpoints in given directory log/spellgcn_rep0_sighan13_CSC_0

```

**Comment by cxysteven** [comment]
The initialized checkpoint~(BERT model chinese) can be download from https://github.com/google-research/bert/blob/master/README.md

**Comment by li-aolong** [comment]
> The initialized checkpoint~(BERT model chinese) can be download from https://github.com/google-research/bert/blob/master/README.md

It's not the BERT model. 
It's `in given directory log/spellgcn_rep0_sighan13_CSC_0`.
I met the same error and found there are also some errors before:
```
ResourceExhaustedError (see above for traceback): OOM when allocating tensor with shape[3072,768] and type float on /job:localhost/replica:0/task:0/device:GPU:0 by allocator GPU_0_bfc
```
So, it may because the model didn't finish well.
